# Generated by Django 4.1.7 on 2023-02-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drinks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drink",
            old_name="descrition",
            new_name="description",
        ),
    ]
